name: Get latest release version
on:
  schedule:
    - cron: "0 10 * * *"
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/gravitational/teleport/releases/latest | \
          jq -r ".tag_name" > version
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        run: |
          VERSION=$(cat version) docker buildx build --platform linux/arm64 ronaldmiranda/teleport-arm:$VERSION --build-arg version=$VERSION --build-arg arch=arm64
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github workflow'
          git config --global user.email 'github@github.com'
          git commit -am "New release version"
          git push
